# NumPy Advanced Operations

This task explores advanced NumPy operations, including:

* Indexing and Slicing
* Broadcasting

Completed tasks include extracting sub-arrays, fancy indexing, and element-wise operations. Demonstrates proficiency in using NumPy for efficient array manipulation.

In [4]:
import numpy as np
from numpy import random

# For serials 1 to 15:
## Indexing and Slicing

1. Given a 2D array of shape (5, 5), extract a 3x3 sub-array starting from the element at position (1, 1).

In [5]:
#generating the random 2D array
ar11 = np.random.randint(0,10,(5,5))
print(f"5*5 2-D Array: \n {ar11}")

#extracting the 3*3 sub-array from the position (1,1)
sub = ar11[1:-1,1:-1]
print(f"Extracted sub-array: \n {sub}")

5*5 2-D Array: 
 [[7 8 0 0 5]
 [3 3 2 2 1]
 [0 8 9 4 4]
 [5 1 0 2 8]
 [4 4 4 8 0]]
Extracted sub-array: 
 [[3 2 2]
 [8 9 4]
 [1 0 2]]


2. From a 3D array of shape (4, 3, 2), extract all elements in the first two rows and all columns of the second slice along the third axis.


In [6]:
#generating the random 3D array
ar111 = np.random.randint(0,10,(4,3,2))
print(f"3-D Array: \n {ar111}")
#extracting the all elements in the first two rows and all columns of the second slice along the third axis. from the position (4, 3, 2)
subb = ar111[1,:2,:]
print(f"Extracted sub-array: \n {subb}")

3-D Array: 
 [[[4 0]
  [1 2]
  [8 2]]

 [[6 0]
  [3 8]
  [1 0]]

 [[0 8]
  [9 4]
  [1 5]]

 [[7 7]
  [2 6]
  [5 4]]]
Extracted sub-array: 
 [[6 0]
 [3 8]]


3. Given an array of integers, use fancy indexing to extract elements at positions [1, 3, 4, 7].

In [7]:
# create a random array integer
arr = np.random.randint(0,10,8)
#initializing indices 
ind = [1,3,4,7]

print(f"Array: {arr}")
print(f"Fancy Indexing, at positions [1,3,4,7]: {arr[ind]}")

Array: [6 2 8 9 8 6 9 0]
Fancy Indexing, at positions [1,3,4,7]: [2 9 8 0]


4. Given a 2D array, use fancy indexing to select rows [0, 2, 3] and columns [1, 3].

In [8]:
# create a random 2-D array integer
ar = np.random.randint(0,10,(5,5))
#initializing indices
rows = np.array([0,2,3])
col = np.array([1,3])
print(f"Array: \n{ar}")
print(f"Fancy Indexing: \n {ar[np.ix_(rows, col)]}")

Array: 
[[6 9 4 5 3]
 [9 5 0 5 4]
 [8 2 9 9 9]
 [6 1 6 1 8]
 [3 9 4 9 6]]
Fancy Indexing: 
 [[9 5]
 [2 9]
 [1 1]]


5. From a 1D array of random integers, extract all elements that are greater than 10.

In [9]:
#creating the random integer array
arr = np.random.randint(0,20,15)

print(f"Array: \n {arr}")
print(f"Extracted array: \n {[x for x in arr if x > 10]}")

Array: 
 [ 4 11  6 15 11 10  9  9 19 14 17  9  9 11 10]
Extracted array: 
 [11, 15, 11, 19, 14, 17, 11]


6. Given a 2D array of shape (5, 5), replace all elements greater than 15 with the value 0.

In [10]:
#creating the random integer array
arr1 = np.random.randint(0,20,(5,5))

print(f"Array: \n {arr1}")

#replasing the entries
arr1[arr1>15] = 0
print(f"Extracted array: \n {arr1}")

Array: 
 [[17  1  0 12  6]
 [12  0 10 17  5]
 [14 18 12  2 11]
 [ 5  6 10  9 16]
 [ 7 18  9 10 12]]
Extracted array: 
 [[ 0  1  0 12  6]
 [12  0 10  0  5]
 [14  0 12  2 11]
 [ 5  6 10  9  0]
 [ 7  0  9 10 12]]


## Broadcasting


1. Add a 1D array of shape (3,) to each row of a 2D array of shape (4, 3).

In [11]:
#Creating the random array
arr1 = np.random.randint(1,10,3)
#Creating the 2D array
arr2 = np.random.randint(1,10,(4,3))
print(f"Original 1D Array: \n {arr1}")
print(f"Original 2D Array: \n {arr2}")
print(f"Addition: \n {arr1 + arr2}")

Original 1D Array: 
 [5 7 9]
Original 2D Array: 
 [[3 7 8]
 [2 8 1]
 [9 5 3]
 [9 9 2]]
Addition: 
 [[ 8 14 17]
 [ 7 15 10]
 [14 12 12]
 [14 16 11]]


2. Multiply a 2D array of shape (3, 3) by a 1D array of shape (3,).

In [12]:
#Creating the Ranadom 1D array
arr1 = np.random.randint(1,10,3)
print(f"Original 1D Array: \n {arr1}")
arr2 = np.random.randint(1,10,(3,3))
print(f"Original 2D Array: \n {arr2}")
print(f"Mutiplication: \n {arr1 * arr2}")

Original 1D Array: 
 [4 5 8]
Original 2D Array: 
 [[9 3 6]
 [8 5 3]
 [7 4 3]]
Mutiplication: 
 [[36 15 48]
 [32 25 24]
 [28 20 24]]


3. Create two 2D arrays of shapes (3, 1) and (1, 4) respectively, and perform element-wise addition.

In [13]:
#Creating the 2D array
arr1 = np.random.randint(1,10,(3,1))
arr2 = np.random.randint(1,10,(1,4))

print(f"Original 2D Array: \n {arr1}")
print(f"Original 2D Array: \n {arr2}")
print(f"Addition: \n {arr1 + arr2}")

Original 2D Array: 
 [[4]
 [7]
 [2]]
Original 2D Array: 
 [[9 3 4 8]]
Addition: 
 [[13  7  8 12]
 [16 10 11 15]
 [11  5  6 10]]


4. Given a 3D array of shape (2, 3, 4), add a 2D array of shape (3, 4) to each 2D slice along the first axis.

In [14]:
#Creating the 3D array
arr1 = np.random.randint(1,10,(2, 3, 4))
#Creating the 2D array
arr2 = np.random.randint(1,10,(3,4))

print(f"Original 3D Array: \n {arr1}")
print(f"Original 2D Array: \n {arr2}")
print(f"Addition: \n {arr2 + arr1[0]}")


Original 3D Array: 
 [[[2 7 6 8]
  [9 8 3 5]
  [8 7 9 8]]

 [[9 7 4 8]
  [3 5 8 7]
  [9 4 5 8]]]
Original 2D Array: 
 [[6 1 1 1]
 [5 2 1 8]
 [1 8 8 2]]
Addition: 
 [[ 8  8  7  9]
 [14 10  4 13]
 [ 9 15 17 10]]


## Some more

1. Given a 2D array, use slicing to extract every second row and every second column, then add a 1D array to each row of the sliced array.

In [15]:
#Creating 2D Array
arr2 = np.random.randint(1,10,(4,4))
#Creating 1D Array
arr1 = np.random.randint(0,10,5)
print(f"Original 2D Array: \n {arr2}")
print(f"Original 1D Array: \n {arr1}")
print(f"Addition: \n {arr1+arr2[1,1]}")

Original 2D Array: 
 [[5 7 1 8]
 [1 9 5 7]
 [9 8 8 9]
 [9 9 9 6]]
Original 1D Array: 
 [7 4 7 0 1]
Addition: 
 [16 13 16  9 10]


2. From a 3D array of shape (4, 3, 2), extract a sub-array using slicing and then use broadcasting to subtract a 2D array from each slice along the third axis.

In [16]:
#Creating 3D array
arr2 = np.random.randint(1,10,(4,3,2))
#Creating 2D array
arr1 = np.random.randint(0,10,(2,2))
print(f"Original 3D Array: \n {arr2}")
print(f"Original 2D Array: \n {arr1}")

sub = arr2[:,0:2,0:2]
print(f"Sub array: \n {sub}")

print(f"Addition: \n {arr1+sub}")

Original 3D Array: 
 [[[5 5]
  [5 2]
  [6 3]]

 [[6 7]
  [6 2]
  [1 9]]

 [[4 6]
  [5 1]
  [3 3]]

 [[2 6]
  [1 5]
  [6 8]]]
Original 2D Array: 
 [[9 4]
 [1 3]]
Sub array: 
 [[[5 5]
  [5 2]]

 [[6 7]
  [6 2]]

 [[4 6]
  [5 1]]

 [[2 6]
  [1 5]]]
Addition: 
 [[[14  9]
  [ 6  5]]

 [[15 11]
  [ 7  5]]

 [[13 10]
  [ 6  4]]

 [[11 10]
  [ 2  8]]]


3. Given a 2D array, extract the diagonal elements and create a 1D array.

In [17]:
#Creating the 2D array
arr1 = np.random.randint(0,10,(4,4))
print(f"Original 2D Array: \n {arr1}")
print(f"Diagnol Entries: \n {np.diag(arr1)}")

Original 2D Array: 
 [[9 0 5 1]
 [7 2 4 5]
 [1 4 6 6]
 [9 0 2 2]]
Diagnol Entries: 
 [9 2 6 2]


4. Use slicing to reverse the order of elements in each row of a 2D array.

In [18]:
#Creating the 2D array
arr1 = np.random.randint(0,10,(4,4))
print(f"Original 2D Array: \n {arr1}")
print(f"Reversed Order: \n {arr1[:,::-1]}")

Original 2D Array: 
 [[1 2 1 4]
 [6 8 4 7]
 [3 0 4 3]
 [1 3 1 8]]
Reversed Order: 
 [[4 1 2 1]
 [7 4 8 6]
 [3 4 0 3]
 [8 1 3 1]]


5. Given a 3D array of shape (4, 5, 6), use slicing to extract a sub-array of shape (2, 3, 4) and then use broadcasting to add a 1D array of shape (4,) to each row along the third axis.

In [19]:
#Creating the 3D array
arr1 = np.random.randint(0,10,(4,5,6))
#Creating the 1D array
arr2 = np.random.randint(0,10,4)
print(f"Original 1D Array: \n {arr1}")
print(f"Original 3D Array: \n {arr2}")

sub = arr1[:2,:3,:4]
print(f"Sub-Array: \n {sub}")
print(f"Addition: \n {arr2+sub}")

Original 1D Array: 
 [[[3 8 6 8 1 1]
  [9 0 9 3 5 8]
  [9 5 5 4 6 4]
  [3 1 0 4 7 9]
  [8 3 3 6 8 3]]

 [[1 4 3 2 9 1]
  [1 8 3 1 6 8]
  [3 2 1 0 8 6]
  [2 1 6 2 9 1]
  [4 7 5 0 3 6]]

 [[0 8 9 2 3 9]
  [5 1 1 1 3 7]
  [2 9 1 2 7 5]
  [3 8 5 2 9 5]
  [5 0 0 3 3 9]]

 [[5 8 2 6 0 0]
  [6 6 8 3 3 8]
  [0 7 2 5 0 6]
  [1 1 7 2 2 0]
  [4 8 1 1 2 0]]]
Original 3D Array: 
 [2 0 1 1]
Sub-Array: 
 [[[3 8 6 8]
  [9 0 9 3]
  [9 5 5 4]]

 [[1 4 3 2]
  [1 8 3 1]
  [3 2 1 0]]]
Addition: 
 [[[ 5  8  7  9]
  [11  0 10  4]
  [11  5  6  5]]

 [[ 3  4  4  3]
  [ 3  8  4  2]
  [ 5  2  2  1]]]


6. Create a 2D array and use both slicing and broadcasting to set the last column to the sum of the first two columns for each row.

In [20]:
#Creating the 2D Array
arr1 = np.random.randint(0,10,(4,5))
print(f"Original: \n {arr1}")

new = arr1[:,:-1]
print(f"Last Column Removed: \n {new}")
print(f"Added first two columnns: \n {new[:,0]+new[:,1]}")

#print((new[:,0]+new[:,1]).reshape(1,-1))
x = (new[:,0]+new[:,1]).reshape(1,-1)
x1 = x[::-1].T
print(f"Converting New: \n {x1}")

print(f"Resulted Array: \n {np.insert(new, 4, x, axis=1)}")

Original: 
 [[9 6 5 0 9]
 [0 0 9 9 0]
 [4 1 9 7 9]
 [9 3 1 3 6]]
Last Column Removed: 
 [[9 6 5 0]
 [0 0 9 9]
 [4 1 9 7]
 [9 3 1 3]]
Added first two columnns: 
 [15  0  5 12]
Converting New: 
 [[15]
 [ 0]
 [ 5]
 [12]]
Resulted Array: 
 [[ 9  6  5  0 15]
 [ 0  0  9  9  0]
 [ 4  1  9  7  5]
 [ 9  3  1  3 12]]


# For serial 16 to last:
## Indexing and Slicing

7. Given a 2D array of shape (6, 6), extract a 2x2 sub-array starting from the element at position (1, 1).


In [21]:
#Creating the 2D array
arr1 = np.random.randint(0,10,(6,6))
print(f"Original: \n {arr1}")
print(f"Sub-Array: \n {arr1[1:3,1:3]}")

Original: 
 [[6 4 1 4 3 1]
 [2 2 7 9 1 6]
 [2 3 6 3 1 2]
 [0 8 7 5 3 7]
 [1 0 7 8 7 5]
 [6 3 8 1 0 3]]
Sub-Array: 
 [[2 7]
 [3 6]]


8. From a 3D array of shape (3, 2, 1), extract all elements in the first two rows and all columns of the second slice along the third axis.


In [22]:
#Creating the 3D array
arr1 = np.random.randint(0,10,(3,2,1))
print(f"Original: \n {arr1}")

print(f"Extracted Array: \n {arr1[1,:2,:]}")

Original: 
 [[[1]
  [1]]

 [[6]
  [1]]

 [[7]
  [8]]]
Extracted Array: 
 [[6]
 [1]]


9. Given an array of integers, use fancy indexing to extract elements at positions [1, 3, 4, 6].


In [23]:
#Creating the random array
arr1 = np.random.randint(0,10,9)
print(f"Original: \n {arr1}")
indicies = [1,3,4,6]
print(f"Extracted Array: \n {arr1[indicies]}")

Original: 
 [4 0 1 9 1 9 4 8 9]
Extracted Array: 
 [0 9 1 4]


10. Given a 2D array, use fancy indexing to select rows [0, 2, 2] and columns [1, 3].


In [24]:
#Creating the 2D array
arr1 = np.random.randint(0,10,(4,5))
print(f"Original: \n {arr1}")
rows = [0,2,2]
col = [1,3]
print(f"Extracting the fancy indexing: \n {arr1[np.ix_(rows, col)]}")

Original: 
 [[7 6 8 4 1]
 [0 0 8 2 6]
 [2 3 0 6 7]
 [6 0 7 6 5]]
Extracting the fancy indexing: 
 [[6 4]
 [3 6]
 [3 6]]


11. From a 1D array of random integers, extract all elements that are greater than 8.


In [25]:
#Creating the random array
arr1 = np.random.randint(0,10,10)
print(f"Original: \n {arr1}")

print(f"Extracted array: \n {arr1[arr1>8]}")

Original: 
 [6 5 0 0 6 6 2 1 5 6]
Extracted array: 
 []


12. Given a 2D array of shape (6, 6), replace all elements greater than 13 with the value 0.

In [26]:
#Creating the 2D array
arr1 = np.random.randint(0,20,(6,6))
print(f"Original: \n {arr1}")
arr1[arr1>13] = 0
print(f"After replacing: \n {arr1}")

Original: 
 [[18 10 15 19  3 14]
 [19  1  8 10 11  6]
 [13  5  6 15  6 12]
 [ 8 15  7 10 17  6]
 [19  5  6  0  6  9]
 [11 17  7  5  1 11]]
After replacing: 
 [[ 0 10  0  0  3  0]
 [ 0  1  8 10 11  6]
 [13  5  6  0  6 12]
 [ 8  0  7 10  0  6]
 [ 0  5  6  0  6  9]
 [11  0  7  5  1 11]]


## Broadcasting

5. Add a 1D array of shape (3,) to each row of a 2D array of shape (4, 3).

In [27]:
#Creating the arrays
arr1 = np.random.randint(0,20,3)
arr2 = np.random.randint(0,20,(4,3))

print(f"1-D Array: \n {arr1}")
print(f"2-D Array: \n {arr2}")
print(f"Addition: \n {arr1+arr2}")

1-D Array: 
 [17  7 12]
2-D Array: 
 [[ 8  9 16]
 [ 3  1  7]
 [ 5  6  1]
 [ 8  9 17]]
Addition: 
 [[25 16 28]
 [20  8 19]
 [22 13 13]
 [25 16 29]]


6. Multiply a 2D array of shape (3, 3) by a 1D array of shape (3,).

In [28]:
#Creating the ararys
arr1 = np.random.randint(0,20,3)
arr2 = np.random.randint(0,20,(3,3))

print(f"1-D Array: \n {arr1}")
print(f"2-D Array: \n {arr2}")
print(f"Multiplication: \n {arr2*arr1}")

1-D Array: 
 [11 10 10]
2-D Array: 
 [[ 0  7  9]
 [ 4  7 11]
 [19 11  7]]
Multiplication: 
 [[  0  70  90]
 [ 44  70 110]
 [209 110  70]]


7. Create two 2D arrays of shapes (3, 1) and (1, 4) respectively, and perform element-wise addition.

In [29]:
#Creating the arrays
arr1 = np.random.randint(0,20,(3,1))
arr2 = np.random.randint(0,20,(1,4))

print(f"1-D Array: \n {arr1}")
print(f"2-D Array: \n {arr2}")
print(f"Addition: \n {arr2+arr1}")

1-D Array: 
 [[ 2]
 [ 3]
 [10]]
2-D Array: 
 [[17  1  9 18]]
Addition: 
 [[19  3 11 20]
 [20  4 12 21]
 [27 11 19 28]]


8. Given a 3D array of shape (2, 3, 4), add a 2D array of shape (3, 4) to each 2D slice along the first axis.

In [30]:
#Creating the arrays
arr1 = np.random.randint(0,20,(2,3,4))
arr2 = np.random.randint(0,20,(3,4))

print(f"3-D Array: \n {arr1}")
print(f"2-D Array: \n {arr2}")
print(f"Addition: \n {arr2+arr1[0]}")

3-D Array: 
 [[[ 1  5 12 16]
  [ 7 11  4  3]
  [ 0  5  8  9]]

 [[ 0 18  5  7]
  [10 15 16 17]
  [ 7 14 12 17]]]
2-D Array: 
 [[11  1 13 14]
 [19 11 17 13]
 [ 7 12 10  3]]
Addition: 
 [[12  6 25 30]
 [26 22 21 16]
 [ 7 17 18 12]]


## Some more

7. Given a 2D array, use slicing to extract every second row and every second column, then add a 1D array to each row of the sliced array.

In [31]:
#Creating the arrays
arr1 = np.random.randint(0,20,3)
arr2 = np.random.randint(0,20,(6,6))

print(f"1-D Array: \n {arr1}")
print(f"2-D Array: \n {arr2}")
print(f"Addition: \n {arr2[::2,::2]+arr1}")

1-D Array: 
 [11 18 14]
2-D Array: 
 [[ 4  8 17 16 12  4]
 [18 19 19  3  9 17]
 [18  2  6 14  1 15]
 [15  8 15  0  5 19]
 [ 2  6 19 13 11  4]
 [15 11  2  5 14 11]]
Addition: 
 [[15 35 26]
 [29 24 15]
 [13 37 25]]


8. From a 3D array of shape (3, 2, 1), extract a sub-array using slicing and then use broadcasting to subtract a 2D array from each slice along the third axis.

In [32]:
#Creating the arrays
arr1 = np.random.randint(0,20,(3,2,1))
arr2 = np.random.randint(0,20,(2,1))

print(f"1-D Array: \n {arr1}")
print(f"2-D Array: \n {arr2}")
print(f"Addition: \n {arr2-arr1}")

1-D Array: 
 [[[13]
  [ 6]]

 [[ 6]
  [ 9]]

 [[11]
  [10]]]
2-D Array: 
 [[ 2]
 [10]]
Addition: 
 [[[-11]
  [  4]]

 [[ -4]
  [  1]]

 [[ -9]
  [  0]]]


9. Given a 2D array, extract the diagonal elements and create a 1D array.

In [33]:
#Creating the arrays
arr2 = np.random.randint(0,20,(4,3))

print(f"2-D Array: \n {arr2}")
print(f"Diagnol Entries: \n {np.diag(arr2)}")

2-D Array: 
 [[ 4  1  9]
 [15 11 10]
 [18 10  0]
 [12 16 17]]
Diagnol Entries: 
 [ 4 11  0]


10. Use slicing to reverse the order of elements in each row of a 2D array.

In [34]:
#Creating the arrays
arr2 = np.random.randint(0,20,(4,3))

print(f"2-D Array: \n {arr2}")
print(f"Reversed: \n {arr2[:,::-1]}")

2-D Array: 
 [[11 19  0]
 [ 5 15  0]
 [ 7 18  7]
 [ 5 17  0]]
Reversed: 
 [[ 0 19 11]
 [ 0 15  5]
 [ 7 18  7]
 [ 0 17  5]]


11. Given a 3D array of shape (7, 6, 5), use slicing to extract a sub-array of shape (2, 3, 4) and then use broadcasting to add a 1D array of shape (4,) to each row along the third axis.

In [35]:
#Creating the arrays
arr1 = np.random.randint(0,20,(7,6,5))
arr2 = np.random.randint(0,20,4)
print(f"3-D Array: \n {arr1}")
print(f"1-D Array: \n {arr2}")
x = arr1[:2,:3,:4]
print(f"Sub-Array: \n {arr1[:2,:3,:4]}")
print(f"Addition: \n {arr2-x}")

3-D Array: 
 [[[15  8  5 16  2]
  [12  3  2 14 12]
  [12  3 14  1  9]
  [15 13 12 16 15]
  [ 9 17  4 14  7]
  [ 5 10 11 16  8]]

 [[ 6 17 19 15  3]
  [ 5  4  8  0 11]
  [ 3 18  7 19  1]
  [ 9  0  2  2 10]
  [ 4 17  8 10  0]
  [ 1  7  6  1 13]]

 [[ 8 17 17  5  2]
  [11 19 10 14  6]
  [ 7 14 14 18  5]
  [ 1 10 12 12  7]
  [16 13  2  8  7]
  [ 3  6  0  8  9]]

 [[14 11 18 17  3]
  [17 15 14 18  0]
  [ 4  9 10 14  2]
  [ 1 10  8  1  3]
  [ 9 19 10 15 11]
  [ 8 16  5  4 12]]

 [[17 12  3  4 12]
  [ 9 10 13 18 14]
  [ 3  7  4  4  4]
  [16  2 11 16 12]
  [14  7  1 10  8]
  [19 16 17  2  2]]

 [[15  5  1 18 18]
  [17 15 14 11  9]
  [ 9 10 17 10 17]
  [11 11 15  8  3]
  [14  8  4  3  9]
  [ 0 12 18 17  2]]

 [[ 2 17  3  6  3]
  [14  7 18 18  0]
  [ 9  3 13 19 18]
  [19  3  8 16 17]
  [ 4 11 10 13 10]
  [ 7  9 13 14  0]]]
1-D Array: 
 [16 16 12  9]
Sub-Array: 
 [[[15  8  5 16]
  [12  3  2 14]
  [12  3 14  1]]

 [[ 6 17 19 15]
  [ 5  4  8  0]
  [ 3 18  7 19]]]
Addition: 
 [[[  1   8   7  -7]
  [

12. Create a 2D array and use both slicing and broadcasting to set the last column to the sum of the first two columns for each row.

In [36]:
#Creating the arrays
arr1 = np.random.randint(0,10,(4,5))
print(f"Original: \n {arr1}")
new = arr1[:,:-1]
print(f"Last Column Removed: \n {new}")
print(f"Added first two columnns: \n {new[:,0]+new[:,1]}")
#print((new[:,0]+new[:,1]).reshape(1,-1))
x = (new[:,0]+new[:,1]).reshape(1,-1)
x1 = x[::-1].T
print(f"Converting New: \n {x1}")

print(f"Resulted Array: \n {np.insert(new, 4, x, axis=1)}")

Original: 
 [[7 2 7 4 5]
 [6 8 2 7 3]
 [3 4 9 1 6]
 [9 8 8 2 7]]
Last Column Removed: 
 [[7 2 7 4]
 [6 8 2 7]
 [3 4 9 1]
 [9 8 8 2]]
Added first two columnns: 
 [ 9 14  7 17]
Converting New: 
 [[ 9]
 [14]
 [ 7]
 [17]]
Resulted Array: 
 [[ 7  2  7  4  9]
 [ 6  8  2  7 14]
 [ 3  4  9  1  7]
 [ 9  8  8  2 17]]


# Practicle Application

# Image Processing Application
## Introduction

This project demonstrates the use of NumPy advanced operations for image processing tasks. The application performs the following tasks:

* Image Cropping
* Image Flipping
* Image Rotation
* Image Filtering
* Image Resizing

Using NumPy arrays and functions, we can efficiently process and manipulate images. This application showcases the power of NumPy in image processing and provides a foundation for more advanced image processing techniques.

In [37]:
import numpy as np

def crop_image(image, size):
    return image[:size[0], :size[1]]

def flip_image(image, axis):
    return np.flip(image, axis)

def rotate_image(image, angle):
    return np.rot90(image, angle)

def resize_image(image, size):
    return np.resize(image, size)

# Example usage
image = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

cropped_image = crop_image(image, (2, 2))
print(f"Cropped Image: \n {cropped_image}")

flipped_image = flip_image(image, 1)
print(f"Flipped Image: \n {flipped_image}")

rotated_image = rotate_image(image, 1)
print(f"Rotated Image: \n {rotated_image}")

resized_image = resize_image(image, (3, 3))
print(f"Resized Image: \n {resized_image}")

Cropped Image: 
 [[1 2]
 [4 5]]
Flipped Image: 
 [[3 2 1]
 [6 5 4]
 [9 8 7]]
Rotated Image: 
 [[3 6 9]
 [2 5 8]
 [1 4 7]]
Resized Image: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
