# Numpy Advance Operations

In [2]:
import numpy as np
from numpy import random

# For serials 1 to 15:
## Indexing and Slicing

1. Given a 2D array of shape (5, 5), extract a 3x3 sub-array starting from the element at position (1, 1).

In [3]:
#generating the random 2D array
ar11 = np.random.randint(0,10,(5,5))
print(f"5*5 2-D Array: \n {ar11}")

#extracting the 3*3 sub-array from the position (1,1)
sub = ar11[1:-1,1:-1]
print(f"Extracted sub-array: \n {sub}")

5*5 2-D Array: 
 [[6 6 9 0 4]
 [8 3 6 5 6]
 [8 1 9 9 6]
 [6 3 2 9 2]
 [1 5 9 9 2]]
Extracted sub-array: 
 [[3 6 5]
 [1 9 9]
 [3 2 9]]


2. From a 3D array of shape (4, 3, 2), extract all elements in the first two rows and all columns of the second slice along the third axis.


In [4]:
#generating the random 3D array
ar111 = np.random.randint(0,10,(4,3,2))
print(f"3-D Array: \n {ar111}")
#extracting the all elements in the first two rows and all columns of the second slice along the third axis. from the position (4, 3, 2)
subb = ar111[1,:2,:]
print(f"Extracted sub-array: \n {subb}")

3-D Array: 
 [[[4 6]
  [7 5]
  [4 2]]

 [[8 4]
  [8 8]
  [9 4]]

 [[3 5]
  [6 6]
  [9 7]]

 [[4 8]
  [8 3]
  [8 6]]]
Extracted sub-array: 
 [[8 4]
 [8 8]]


3. Given an array of integers, use fancy indexing to extract elements at positions [1, 3, 4, 7].

In [5]:
# create a random array integer
arr = np.random.randint(0,10,8)
#initializing indices 
ind = [1,3,4,7]

print(f"Array: {arr}")
print(f"Fancy Indexing, at positions [1,3,4,7]: {arr[ind]}")

Array: [1 8 3 4 8 3 1 2]
Fancy Indexing, at positions [1,3,4,7]: [8 4 8 2]


4. Given a 2D array, use fancy indexing to select rows [0, 2, 3] and columns [1, 3].

In [6]:
# create a random 2-D array integer
ar = np.random.randint(0,10,(5,5))
#initializing indices
rows = np.array([0,2,3])
col = np.array([1,3])
print(f"Array: \n{ar}")
print(f"Fancy Indexing: \n {ar[np.ix_(rows, col)]}")

Array: 
[[9 7 5 8 1]
 [2 0 3 9 0]
 [6 5 4 1 2]
 [1 6 3 2 4]
 [7 8 1 8 9]]
Fancy Indexing: 
 [[7 8]
 [5 1]
 [6 2]]


5. From a 1D array of random integers, extract all elements that are greater than 10.

In [7]:
#creating the random integer array
arr = np.random.randint(0,20,15)

print(f"Array: \n {arr}")
print(f"Extracted array: \n {[x for x in arr if x > 10]}")

Array: 
 [10 18 15 10  8 17 17  2  3  5 14  0 10  0  4]
Extracted array: 
 [18, 15, 17, 17, 14]


6. Given a 2D array of shape (5, 5), replace all elements greater than 15 with the value 0.

In [8]:
#creating the random integer array
arr1 = np.random.randint(0,20,(5,5))

print(f"Array: \n {arr1}")

#replasing the entries
arr1[arr1>15] = 0
print(f"Extracted array: \n {arr1}")

Array: 
 [[ 5  6 10 10 18]
 [12 17 11  0 17]
 [12 10 13 13  1]
 [19  9 19  5 11]
 [18 16 10  6 17]]
Extracted array: 
 [[ 5  6 10 10  0]
 [12  0 11  0  0]
 [12 10 13 13  1]
 [ 0  9  0  5 11]
 [ 0  0 10  6  0]]


## Broadcasting


1. Add a 1D array of shape (3,) to each row of a 2D array of shape (4, 3).

In [10]:
#Creating the random array
arr1 = np.random.randint(1,10,3)
#Creating the 2D array
arr2 = np.random.randint(1,10,(4,3))
print(f"Original 1D Array: \n {arr1}")
print(f"Original 2D Array: \n {arr2}")
print(f"Addition: \n {arr1 + arr2}")

Original 1D Array: 
 [2 2 3]
Original 2D Array: 
 [[3 1 2]
 [5 3 3]
 [8 2 9]
 [2 3 7]]
Addition: 
 [[ 5  3  5]
 [ 7  5  6]
 [10  4 12]
 [ 4  5 10]]


2. Multiply a 2D array of shape (3, 3) by a 1D array of shape (3,).

In [11]:
#Creating the Ranadom 1D array
arr1 = np.random.randint(1,10,3)
print(f"Original 1D Array: \n {arr1}")
arr2 = np.random.randint(1,10,(3,3))
print(f"Original 2D Array: \n {arr2}")
print(f"Mutiplication: \n {arr1 * arr2}")

Original 1D Array: 
 [9 6 2]
Original 2D Array: 
 [[1 5 8]
 [2 2 3]
 [6 3 8]]
Mutiplication: 
 [[ 9 30 16]
 [18 12  6]
 [54 18 16]]


3. Create two 2D arrays of shapes (3, 1) and (1, 4) respectively, and perform element-wise addition.

In [12]:
#Creating the 2D array
arr1 = np.random.randint(1,10,(3,1))
arr2 = np.random.randint(1,10,(1,4))

print(f"Original 2D Array: \n {arr1}")
print(f"Original 2D Array: \n {arr2}")
print(f"Addition: \n {arr1 + arr2}")

Original 2D Array: 
 [[6]
 [1]
 [9]]
Original 2D Array: 
 [[3 8 5 1]]
Addition: 
 [[ 9 14 11  7]
 [ 4  9  6  2]
 [12 17 14 10]]


4. Given a 3D array of shape (2, 3, 4), add a 2D array of shape (3, 4) to each 2D slice along the first axis.

In [13]:
#Creating the 3D array
arr1 = np.random.randint(1,10,(2, 3, 4))
#Creating the 2D array
arr2 = np.random.randint(1,10,(3,4))

print(f"Original 3D Array: \n {arr1}")
print(f"Original 2D Array: \n {arr2}")
print(f"Addition: \n {arr2 + arr1[0]}")


Original 3D Array: 
 [[[7 6 1 5]
  [4 7 2 9]
  [7 9 5 1]]

 [[8 3 6 8]
  [5 8 3 3]
  [5 8 8 3]]]
Original 2D Array: 
 [[9 3 3 8]
 [8 6 9 6]
 [2 7 7 6]]
Addition: 
 [[16  9  4 13]
 [12 13 11 15]
 [ 9 16 12  7]]


## Some more

1. Given a 2D array, use slicing to extract every second row and every second column, then add a 1D array to each row of the sliced array.

In [14]:
#Creating 2D Array
arr2 = np.random.randint(1,10,(4,4))
#Creating 1D Array
arr1 = np.random.randint(0,10,5)
print(f"Original 2D Array: \n {arr2}")
print(f"Original 1D Array: \n {arr1}")
print(f"Addition: \n {arr1+arr2[1,1]}")

Original 2D Array: 
 [[1 6 5 4]
 [9 8 2 7]
 [3 5 9 4]
 [3 6 2 4]]
Original 1D Array: 
 [0 7 0 3 8]
Addition: 
 [ 8 15  8 11 16]


2. From a 3D array of shape (4, 3, 2), extract a sub-array using slicing and then use broadcasting to subtract a 2D array from each slice along the third axis.

In [15]:
#Creating 3D array
arr2 = np.random.randint(1,10,(4,3,2))
#Creating 2D array
arr1 = np.random.randint(0,10,(2,2))
print(f"Original 3D Array: \n {arr2}")
print(f"Original 2D Array: \n {arr1}")

sub = arr2[:,0:2,0:2]
print(f"Sub array: \n {sub}")

print(f"Addition: \n {arr1+sub}")

Original 3D Array: 
 [[[3 6]
  [2 1]
  [8 2]]

 [[5 1]
  [4 6]
  [8 2]]

 [[1 4]
  [4 7]
  [8 8]]

 [[9 5]
  [5 8]
  [8 2]]]
Original 2D Array: 
 [[9 5]
 [9 7]]
Sub array: 
 [[[3 6]
  [2 1]]

 [[5 1]
  [4 6]]

 [[1 4]
  [4 7]]

 [[9 5]
  [5 8]]]
Addition: 
 [[[12 11]
  [11  8]]

 [[14  6]
  [13 13]]

 [[10  9]
  [13 14]]

 [[18 10]
  [14 15]]]


3. Given a 2D array, extract the diagonal elements and create a 1D array.

In [16]:
#Creating the 2D array
arr1 = np.random.randint(0,10,(4,4))
print(f"Original 2D Array: \n {arr1}")
print(f"Diagnol Entries: \n {np.diag(arr1)}")

Original 2D Array: 
 [[0 8 7 7]
 [2 7 5 4]
 [6 9 4 1]
 [5 0 9 1]]
Diagnol Entries: 
 [0 7 4 1]


4. Use slicing to reverse the order of elements in each row of a 2D array.

In [17]:
#Creating the 2D array
arr1 = np.random.randint(0,10,(4,4))
print(f"Original 2D Array: \n {arr1}")
print(f"Reversed Order: \n {arr1[:,::-1]}")

Original 2D Array: 
 [[0 5 6 8]
 [8 3 0 2]
 [7 1 5 4]
 [4 9 4 8]]
Reversed Order: 
 [[8 6 5 0]
 [2 0 3 8]
 [4 5 1 7]
 [8 4 9 4]]


5. Given a 3D array of shape (4, 5, 6), use slicing to extract a sub-array of shape (2, 3, 4) and then use broadcasting to add a 1D array of shape (4,) to each row along the third axis.

In [18]:
#Creating the 3D array
arr1 = np.random.randint(0,10,(4,5,6))
#Creating the 1D array
arr2 = np.random.randint(0,10,4)
print(f"Original 1D Array: \n {arr1}")
print(f"Original 3D Array: \n {arr2}")

sub = arr1[:2,:3,:4]
print(f"Sub-Array: \n {sub}")
print(f"Addition: \n {arr2+sub}")

Original 1D Array: 
 [[[9 0 9 3 9 6]
  [3 7 3 6 7 4]
  [6 7 6 7 1 2]
  [8 4 5 2 2 1]
  [4 8 9 3 2 5]]

 [[4 1 7 4 3 9]
  [2 6 9 6 6 6]
  [5 8 0 9 4 8]
  [2 9 6 3 7 6]
  [0 7 0 7 0 2]]

 [[4 8 5 2 1 4]
  [0 2 4 7 9 1]
  [0 8 1 8 2 4]
  [2 3 2 5 9 8]
  [7 9 0 6 1 0]]

 [[2 6 8 3 8 5]
  [3 0 0 3 9 4]
  [2 4 1 1 0 8]
  [0 1 4 7 6 5]
  [5 3 1 0 5 6]]]
Original 3D Array: 
 [4 2 4 4]
Sub-Array: 
 [[[9 0 9 3]
  [3 7 3 6]
  [6 7 6 7]]

 [[4 1 7 4]
  [2 6 9 6]
  [5 8 0 9]]]
Addition: 
 [[[13  2 13  7]
  [ 7  9  7 10]
  [10  9 10 11]]

 [[ 8  3 11  8]
  [ 6  8 13 10]
  [ 9 10  4 13]]]


6. Create a 2D array and use both slicing and broadcasting to set the last column to the sum of the first two columns for each row.

In [20]:
#Creating the 2D Array
arr1 = np.random.randint(0,10,(4,5))
print(f"Original: \n {arr1}")

new = arr1[:,:-1]
print(f"Last Column Removed: \n {new}")
print(f"Added first two columnns: \n {new[:,0]+new[:,1]}")

#print((new[:,0]+new[:,1]).reshape(1,-1))
x = (new[:,0]+new[:,1]).reshape(1,-1)
x1 = x[::-1].T
print(f"Converting New: \n {x1}")

print(f"Resulted Array: \n {np.insert(new, 4, x, axis=1)}")

Original: 
 [[7 9 9 5 5]
 [9 9 6 7 3]
 [6 9 0 4 1]
 [8 6 5 6 6]]
Last Column Removed: 
 [[7 9 9 5]
 [9 9 6 7]
 [6 9 0 4]
 [8 6 5 6]]
Added first two columnns: 
 [16 18 15 14]
Converting New: 
 [[16]
 [18]
 [15]
 [14]]
Resulted Array: 
 [[ 7  9  9  5 16]
 [ 9  9  6  7 18]
 [ 6  9  0  4 15]
 [ 8  6  5  6 14]]


# For serial 16 to last:
## Indexing and Slicing

7. Given a 2D array of shape (6, 6), extract a 2x2 sub-array starting from the element at position (1, 1).


In [21]:
#Creating the 2D array
arr1 = np.random.randint(0,10,(6,6))
print(f"Original: \n {arr1}")
print(f"Sub-Array: \n {arr1[1:3,1:3]}")

Original: 
 [[5 0 1 0 5 0]
 [2 6 4 9 2 6]
 [5 8 8 9 5 7]
 [3 8 9 5 6 1]
 [1 2 4 2 2 7]
 [6 3 5 7 2 7]]
Sub-Array: 
 [[6 4]
 [8 8]]


8. From a 3D array of shape (3, 2, 1), extract all elements in the first two rows and all columns of the second slice along the third axis.


In [23]:
#Creating the 3D array
arr1 = np.random.randint(0,10,(3,2,1))
print(f"Original: \n {arr1}")

print(f"Extracted Array: \n {arr1[1,:2,:]}")

Original: 
 [[[7]
  [7]]

 [[8]
  [5]]

 [[2]
  [1]]]
Extracted Array: 
 [[8]
 [5]]


9. Given an array of integers, use fancy indexing to extract elements at positions [1, 3, 4, 6].


In [24]:
#Creating the random array
arr1 = np.random.randint(0,10,9)
print(f"Original: \n {arr1}")
indicies = [1,3,4,6]
print(f"Extracted Array: \n {arr1[indicies]}")

Original: 
 [2 6 0 5 4 8 2 1 0]
Extracted Array: 
 [6 5 4 2]


10. Given a 2D array, use fancy indexing to select rows [0, 2, 2] and columns [1, 3].


In [25]:
#Creating the 2D array
arr1 = np.random.randint(0,10,(4,5))
print(f"Original: \n {arr1}")
rows = [0,2,2]
col = [1,3]
print(f"Extracting the fancy indexing: \n {arr1[np.ix_(rows, col)]}")

Original: 
 [[0 3 1 6 4]
 [0 0 5 7 2]
 [5 0 5 5 0]
 [2 4 6 6 2]]
Extracting the fancy indexing: 
 [[3 6]
 [0 5]
 [0 5]]


11. From a 1D array of random integers, extract all elements that are greater than 8.


In [27]:
#Creating the random array
arr1 = np.random.randint(0,10,10)
print(f"Original: \n {arr1}")

print(f"Extracted array: \n {arr1[arr1>8]}")

Original: 
 [7 9 2 1 5 5 7 7 9 8]
Extracted array: 
 [9 9]


12. Given a 2D array of shape (6, 6), replace all elements greater than 13 with the value 0.

In [28]:
#Creating the 2D array
arr1 = np.random.randint(0,20,(6,6))
print(f"Original: \n {arr1}")
arr1[arr1>13] = 0
print(f"After replacing: \n {arr1}")

Original: 
 [[ 9 10 10  5  4 18]
 [17 14  0 19 16 17]
 [10 13  4  9 11 16]
 [18 18  9 15 11  2]
 [ 0  8  4  3  2 15]
 [13 16 18  4 10  5]]
After replacing: 
 [[ 9 10 10  5  4  0]
 [ 0  0  0  0  0  0]
 [10 13  4  9 11  0]
 [ 0  0  9  0 11  2]
 [ 0  8  4  3  2  0]
 [13  0  0  4 10  5]]


## Broadcasting

5. Add a 1D array of shape (3,) to each row of a 2D array of shape (4, 3).

In [29]:
#Creating the arrays
arr1 = np.random.randint(0,20,3)
arr2 = np.random.randint(0,20,(4,3))

print(f"1-D Array: \n {arr1}")
print(f"2-D Array: \n {arr2}")
print(f"Addition: \n {arr1+arr2}")

1-D Array: 
 [13 16  1]
2-D Array: 
 [[ 7 16 17]
 [ 1 17  8]
 [ 7 18  1]
 [ 5 16 16]]
Addition: 
 [[20 32 18]
 [14 33  9]
 [20 34  2]
 [18 32 17]]


6. Multiply a 2D array of shape (3, 3) by a 1D array of shape (3,).

In [30]:
#Creating the ararys
arr1 = np.random.randint(0,20,3)
arr2 = np.random.randint(0,20,(3,3))

print(f"1-D Array: \n {arr1}")
print(f"2-D Array: \n {arr2}")
print(f"Multiplication: \n {arr2*arr1}")

1-D Array: 
 [15 19  5]
2-D Array: 
 [[15  1 12]
 [15  7  6]
 [ 0  8 16]]
Multiplication: 
 [[225  19  60]
 [225 133  30]
 [  0 152  80]]


7. Create two 2D arrays of shapes (3, 1) and (1, 4) respectively, and perform element-wise addition.

In [31]:
#Creating the arrays
arr1 = np.random.randint(0,20,(3,1))
arr2 = np.random.randint(0,20,(1,4))

print(f"1-D Array: \n {arr1}")
print(f"2-D Array: \n {arr2}")
print(f"Addition: \n {arr2+arr1}")

1-D Array: 
 [[ 0]
 [10]
 [16]]
2-D Array: 
 [[17  1  0  2]]
Addition: 
 [[17  1  0  2]
 [27 11 10 12]
 [33 17 16 18]]


8. Given a 3D array of shape (2, 3, 4), add a 2D array of shape (3, 4) to each 2D slice along the first axis.

In [32]:
#Creating the arrays
arr1 = np.random.randint(0,20,(2,3,4))
arr2 = np.random.randint(0,20,(3,4))

print(f"3-D Array: \n {arr1}")
print(f"2-D Array: \n {arr2}")
print(f"Addition: \n {arr2+arr1[0]}")

3-D Array: 
 [[[ 7  3  7 14]
  [13 13 10 14]
  [10  8  7  9]]

 [[ 1  5  2  8]
  [ 9 16  9 16]
  [ 6 12  7  7]]]
2-D Array: 
 [[ 2 15 19 10]
 [10 19  1  4]
 [ 6 10 14 15]]
Addition: 
 [[ 9 18 26 24]
 [23 32 11 18]
 [16 18 21 24]]


## Some more

7. Given a 2D array, use slicing to extract every second row and every second column, then add a 1D array to each row of the sliced array.

In [33]:
#Creating the arrays
arr1 = np.random.randint(0,20,3)
arr2 = np.random.randint(0,20,(6,6))

print(f"1-D Array: \n {arr1}")
print(f"2-D Array: \n {arr2}")
print(f"Addition: \n {arr2[::2,::2]+arr1}")

1-D Array: 
 [ 2 15  5]
2-D Array: 
 [[12  9 11  2  1 19]
 [15  3 17 10 16 17]
 [ 2  9  7 15  5  6]
 [ 1  3  4  9 12  6]
 [ 9  5 15  5  7 12]
 [16 18 13 18  0  8]]
Addition: 
 [[14 26  6]
 [ 4 22 10]
 [11 30 12]]


8. From a 3D array of shape (3, 2, 1), extract a sub-array using slicing and then use broadcasting to subtract a 2D array from each slice along the third axis.

In [34]:
#Creating the arrays
arr1 = np.random.randint(0,20,(3,2,1))
arr2 = np.random.randint(0,20,(2,1))

print(f"1-D Array: \n {arr1}")
print(f"2-D Array: \n {arr2}")
print(f"Addition: \n {arr2-arr1}")

1-D Array: 
 [[[ 6]
  [ 6]]

 [[ 2]
  [10]]

 [[ 7]
  [14]]]
2-D Array: 
 [[4]
 [2]]
Addition: 
 [[[ -2]
  [ -4]]

 [[  2]
  [ -8]]

 [[ -3]
  [-12]]]


9. Given a 2D array, extract the diagonal elements and create a 1D array.

In [35]:
#Creating the arrays
arr2 = np.random.randint(0,20,(4,3))

print(f"2-D Array: \n {arr2}")
print(f"Diagnol Entries: \n {np.diag(arr2)}")

2-D Array: 
 [[ 8  1  6]
 [18 10  9]
 [ 3  9 17]
 [12  3  1]]
Diagnol Entries: 
 [ 8 10 17]


10. Use slicing to reverse the order of elements in each row of a 2D array.

In [36]:
#Creating the arrays
arr2 = np.random.randint(0,20,(4,3))

print(f"2-D Array: \n {arr2}")
print(f"Reversed: \n {arr2[:,::-1]}")

2-D Array: 
 [[ 1 19  3]
 [19  1 14]
 [18 13  7]
 [ 1  9  3]]
Reversed: 
 [[ 3 19  1]
 [14  1 19]
 [ 7 13 18]
 [ 3  9  1]]


11. Given a 3D array of shape (7, 6, 5), use slicing to extract a sub-array of shape (2, 3, 4) and then use broadcasting to add a 1D array of shape (4,) to each row along the third axis.

In [37]:
#Creating the arrays
arr1 = np.random.randint(0,20,(7,6,5))
arr2 = np.random.randint(0,20,4)
print(f"3-D Array: \n {arr1}")
print(f"1-D Array: \n {arr2}")
x = arr1[:2,:3,:4]
print(f"Sub-Array: \n {arr1[:2,:3,:4]}")
print(f"Addition: \n {arr2-x}")

3-D Array: 
 [[[ 9  2 12  6  2]
  [ 8 15  9 16 10]
  [ 2  6 16  3 18]
  [13  8 12 14 15]
  [ 1  6  9  5 12]
  [14  2 16  6 17]]

 [[ 2  5 15  2 11]
  [15  7  1 18 18]
  [ 4 10  7  2 15]
  [18  0  4 13 15]
  [16  1  7  8  0]
  [19 10 14  6  3]]

 [[13 14  1  8  2]
  [16  4  5 12  5]
  [16  3  6  4 15]
  [ 5 18  2  3 14]
  [ 7 12  7 18 15]
  [19  5 19  1 16]]

 [[ 5  9  0  0 11]
  [ 8 11 17  4 19]
  [ 0 12 13  7 18]
  [16 19 14 13  9]
  [ 4 16 15 13  6]
  [15 19  8 13  6]]

 [[ 8  1  3 12 13]
  [13  7  0  5 11]
  [16 17 10 12  1]
  [ 6  3  3 15 12]
  [16  2 16  4 10]
  [ 1 16 10 10  9]]

 [[ 3 10  5  8  7]
  [15 15 19 13 19]
  [13  8 11  0 14]
  [16 11 19  0  5]
  [16  7 10  3  3]
  [17 13  0  2  8]]

 [[ 0  4  0 16  1]
  [ 2 10 17 10 14]
  [ 7  7  1  9 18]
  [17  3 12  1 10]
  [12  2  4 11  2]
  [10  8  4 19  3]]]
1-D Array: 
 [ 6 18 18 18]
Sub-Array: 
 [[[ 9  2 12  6]
  [ 8 15  9 16]
  [ 2  6 16  3]]

 [[ 2  5 15  2]
  [15  7  1 18]
  [ 4 10  7  2]]]
Addition: 
 [[[-3 16  6 12]
  [-2  

12. Create a 2D array and use both slicing and broadcasting to set the last column to the sum of the first two columns for each row.

In [39]:
#Creating the arrays
arr1 = np.random.randint(0,10,(4,5))
print(f"Original: \n {arr1}")
new = arr1[:,:-1]
print(f"Last Column Removed: \n {new}")
print(f"Added first two columnns: \n {new[:,0]+new[:,1]}")
#print((new[:,0]+new[:,1]).reshape(1,-1))
x = (new[:,0]+new[:,1]).reshape(1,-1)
x1 = x[::-1].T
print(f"Converting New: \n {x1}")

print(f"Resulted Array: \n {np.insert(new, 4, x, axis=1)}")

Original: 
 [[2 5 6 0 8]
 [7 3 4 9 1]
 [6 2 5 4 8]
 [0 6 0 9 4]]
Last Column Removed: 
 [[2 5 6 0]
 [7 3 4 9]
 [6 2 5 4]
 [0 6 0 9]]
Added first two columnns: 
 [ 7 10  8  6]
Converting New: 
 [[ 7]
 [10]
 [ 8]
 [ 6]]
Resulted Array: 
 [[ 2  5  6  0  7]
 [ 7  3  4  9 10]
 [ 6  2  5  4  8]
 [ 0  6  0  9  6]]
